# Generated by Django 3.1.4 on 2021-01-21 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0010_auto_20210121_1557'),
        ('donation', '0003_userbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbank',
            name='permission',
            field=models.IntegerField(choices=[(0, 'View'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userbank',
            unique_together={('user', 'bank')},
        ),
    ]
