# Generated by Django 3.1.4 on 2021-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20210121_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbank',
            old_name='permission',
            new_name='perm',
        ),
        migrations.AlterField(
            model_name='donation',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
