# Generated by Django 3.1.4 on 2021-01-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
