# Generated by Django 3.1.4 on 2021-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210120_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredbank',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
