# Generated by Django 3.1.4 on 2021-01-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20210121_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={},
        ),
    ]
