# Generated by Django 3.1.4 on 2021-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20210121_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
