# Generated by Django 3.1.4 on 2021-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210119_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
