# Generated by Django 3.1.4 on 2021-01-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_reputation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol'))},
        ),
    ]
