# Generated by Django 3.1.4 on 2021-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210121_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBank',
        ),
    ]
