# Generated by Django 3.1.4 on 2021-01-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210124_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='user/egg.jpg', upload_to=''),
        ),
    ]
