# Generated by Django 3.1.4 on 2021-01-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_dp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dp',
            new_name='profile_pic',
        ),
    ]
