# Generated by Django 3.1.5 on 2021-01-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210124_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='user/egg.jpg', upload_to='user/'),
        ),
    ]
